openapi: 3.1.0
info:
  title: Chronocat Satori
  version: 0.0.50
  description: |
    # Chronocat Satori OpenAPI 定义

    这是一份 Chronocat Satori OpenAPI 的完整定义文件。

    任何时候，你都可以从 <https://chronocat.vercel.app/openapi.yaml> 获取到此文件。
  contact:
    name: Team Chrononeko
    url: https://github.com/chrononeko
  license:
    name: AGPL-3.0
    url: https://www.gnu.org/licenses/agpl-3.0.html
externalDocs:
  description: Chronocat 文档
  url: https://chronocat.vercel.app
servers:
  - url: '{protocol}://{host}:{port}/{version}'
    description: Chronocat Satori 服务
    variables:
      protocol:
        default: http
      host:
        default: localhost
      port:
        default: '5500'
      version:
        default: v1
tags:
  - name: Channel
    description: 「频道」——消息的集合。不管文字还是语音都是在频道内发生的。
    externalDocs:
      description: 概念介绍
      url: https://chronocat.vercel.app/develop/satori/fundamentals
  - name: Guild
    description: 「群组」——用户的集合。一个群组包含一组用户和一组频道。
    externalDocs:
      description: 概念介绍
      url: https://chronocat.vercel.app/develop/satori/fundamentals
  - name: GuildMember
    description: 「群组成员」——用户在特定群组内的信息。
    externalDocs:
      description: 概念介绍
      url: https://chronocat.vercel.app/develop/satori/fundamentals
  - name: GuildRole
    description: 「群组角色」——用户在群组内的角色或权限。
    externalDocs:
      description: 概念介绍
      url: https://chronocat.vercel.app/develop/satori/fundamentals
  - name: Login
    description: 「登录信息」——实现侧当前的状态。
    externalDocs:
      description: 概念介绍
      url: https://chronocat.vercel.app/develop/satori/fundamentals
  - name: Message
    description: 「消息」——频道中发送的内容。
    externalDocs:
      description: 概念介绍
      url: https://chronocat.vercel.app/develop/satori/fundamentals
  - name: Reaction
    description: 「表态」——用户对消息的回应。
    externalDocs:
      description: 概念介绍
      url: https://chronocat.vercel.app/develop/satori/fundamentals
  - name: User
    description: 「用户」——群组内的个体。
    externalDocs:
      description: 概念介绍
      url: https://chronocat.vercel.app/develop/satori/fundamentals
security:
  - satori: []
paths:
  /:
    get:
      summary: Satori 欢迎页
      description: 展示 Satori 欢迎页面。无任何实际用途。
      responses:
        '200':
          description: 成功返回 Satori 欢迎页
          content:
            text/html:
              schema:
                type: string
                const: <html>（Satori 欢迎页的 HTML 内容）</html>
      security:
        - {}
  /assets/{assetData}:
    get:
      operationId: assets
      summary: 获取单个资源
      description: |
        获取单个资源。该 URL 通常为 Satori 服务生成并在事件携带的消息元素中出现。
        如果客户端无法通过此链接访问到 Chronocat Satori 服务，则需修改配置文件中的 `self_url` 项。
      parameters:
        - name: assetData
          in: path
          description: 资源信息。通常为 Satori 服务生成。
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 成功获取资源
          content:
            '*/*': {}
      security:
        - {}
  /login.get:
    post:
      operationId: loginGet
      tags:
        - Login
      summary: 获取登录信息
      description: 获取登录信息。
      responses:
        '200':
          description: 成功获取登录信息
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Login'
        '500':
          $ref: '#/components/responses/500'
  /message.create:
    post:
      operationId: messageCreate
      tags:
        - Message
      summary: 发送消息
      description: 发送一条消息。
      requestBody:
        description: 发送的目标和消息内容
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MessageCreatePayload'
      responses:
        '200':
          description: 成功发送消息
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Message'
        '500':
          $ref: '#/components/responses/500'
components:
  securitySchemes:
    satori:
      description: Satori 服务密码
      type: http
      scheme: bearer
      in: header
      bearerFormat: string
  responses:
    '500':
      description: Chronocat 内部错误 (500)
      content:
        text/plain:
          schema:
            type: string
            const: 500 internal error
  schemas:
    Event:
      type: object
      properties:
        id:
          description: 事件 ID
          type: number
        type:
          description: 事件类型
          type: string
        platform:
          description: 接收者的平台名称
          type: string
        self_id:
          description: 接收者的平台账号
          type: string
        timestamp:
          description: 事件的时间戳
          type: number
        channel:
          $ref: '#/components/schemas/Channel'
          description: 事件所属的频道
        guild:
          $ref: '#/components/schemas/Guild'
          description: 事件所属的群组
        login:
          $ref: '#/components/schemas/Login'
          description: 事件的登录信息
        member:
          $ref: '#/components/schemas/GuildMember'
          description: 事件的目标成员
        message:
          $ref: '#/components/schemas/Message'
          description: 事件的消息
        operator:
          $ref: '#/components/schemas/User'
          description: 事件的操作者
        role:
          $ref: '#/components/schemas/GuildRole'
          description: 事件的目标角色
        user:
          $ref: '#/components/schemas/User'
          description: 事件的目标用户
      defaultProperties: []
      additionalProperties: false
      required:
        - id
        - platform
        - self_id
        - timestamp
        - type
    Channel:
      type: object
      properties:
        id:
          description: 频道 ID
          type: string
        name:
          description: 频道名称
          type: string
        type:
          $ref: '#/components/schemas/ChannelType'
          description: 频道类型
        parent_id:
          description: 父频道 ID
          type: string
        avatar:
          description: 不安全的频道头像
          type: string
      defaultProperties: []
      additionalProperties: false
      required:
        - avatar
        - id
        - name
        - parent_id
        - type
    ChannelType:
      type: number
      enum:
        - 0
        - 1
        - 2
        - 3
    Guild:
      type: object
      properties:
        id:
          description: 群组 ID
          type: string
        name:
          description: 群组名称
          type: string
        avatar:
          description: 不安全的群组头像
          type: string
      defaultProperties: []
      additionalProperties: false
      required:
        - avatar
        - id
        - name
    Login:
      type: object
      properties:
        user:
          $ref: '#/components/schemas/User'
          description: 用户对象
        self_id:
          description: 平台账号
          type: string
        platform:
          description: 平台名称
          type: string
        status:
          $ref: '#/components/schemas/LoginStatus'
          description: 在线状态
      defaultProperties: []
      additionalProperties: false
      required:
        - status
    LoginStatus:
      type: number
      enum:
        - 0
        - 1
        - 2
        - 3
        - 4
    GuildMember:
      type: object
      properties:
        user:
          $ref: '#/components/schemas/User'
          description: 用户对象
        name:
          description: 用户在群组中的名称
          type: string
        avatar:
          description: 用户在群组中的头像
          type: string
      defaultProperties: []
      additionalProperties: false
    Message:
      type: object
      properties:
        id:
          description: 消息 ID
          type: string
        content:
          description: 消息内容
          type: string
        channel:
          $ref: '#/components/schemas/Channel'
          description: 频道对象
        guild:
          $ref: '#/components/schemas/Guild'
          description: 群组对象
        member:
          $ref: '#/components/schemas/GuildMember'
          description: 成员对象
        user:
          $ref: '#/components/schemas/User'
          description: 用户对象
        created_at:
          description: 消息发送的时间戳
          type: number
        updated_at:
          description: 消息修改的时间戳
          type: number
      defaultProperties: []
      additionalProperties: false
      required:
        - content
        - id
    User:
      type: object
      properties:
        id:
          description: 用户 ID
          type: string
        name:
          description: 用户名称
          type: string
        avatar:
          description: 用户头像
          type: string
        is_bot:
          description: 是否为机器人
          type: boolean
      defaultProperties: []
      additionalProperties: false
      required:
        - id
        - name
    GuildRole:
      type: object
      properties:
        id:
          description: 角色 ID
          type: string
        name:
          description: 角色名称
          type: string
      defaultProperties: []
      additionalProperties: false
      required:
        - id
    MessageCreatePayload:
      type: object
      properties:
        channel_id:
          title: 目标频道
          description: |-
            消息要发送到的频道。

            在 Chronocat，群聊对应的频道为群号，
            私聊对应的频道为 private: 后跟 QQ 号。
          type: string
        content:
          title: 消息内容
          description: |-
            消息的内容。

            格式为 Satori 消息元素字符串。
          type: string
      defaultProperties: []
      additionalProperties: false
      required:
        - channel_id
        - content
