name: build

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: write
  discussions: write

jobs:
  build:
    name: build

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'false'
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Build Packages
        run: |
          yarn
          yarn build
        shell: bash

      - name: Upload Core Packages
        uses: actions/upload-artifact@v3
        with:
          name: chronocat-pkgs-${{ github.sha }}
          path: build/dist/*.tgz

      - name: Upload LiteLoaderQQNT-Plugin-Chronocat
        uses: actions/upload-artifact@v3
        with:
          name: chronocat-llqqnt-${{ github.sha }}
          path: build/dist/llqqnt

      - name: Upload qqntim-plugin-chronocat
        uses: actions/upload-artifact@v3
        with:
          name: chronocat-qqntim-${{ github.sha }}
          path: build/dist/qqntim

      - name: Upload IIFE
        uses: actions/upload-artifact@v3
        with:
          name: chronocat-iife-${{ github.sha }}
          path: build/dist/iife

      - name: Zip Packages
        run: |
          pwd && ls -l build/dist
          cd build/dist/qqntim
          zip -r ../chronocat-qqntim.zip *
          cd ../llqqnt
          zip -r ../chronocat-llqqnt.zip *
          cd ../
          rm -rf llqqnt qqntim
          pwd && ls -l
          cd ../../
        shell: bash

      - name: Get Version
        id: version
        uses: ashley-taylor/read-json-property-action@v1.0
        with:
          path: ./packages/core/package.json
          property: version

      - name: Create Release and Upload Release Asset
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/heads/main')
        with:
          tag_name: v${{steps.version.outputs.value}}
          name: 发布 v${{steps.version.outputs.value}} 版本
          draft: false
          prerelease: false
          files: |
            build/dist/*.tgz
            build/dist/chronocat-qqntim.zip
            build/dist/chronocat-llqqnt.zip
